version: '3'
services:
  vaccination_card:
    container_name: vaccination_card
    build: .
    command: /bin/bash docker_start.sh
    volumes:
      - .:/vaccination_card
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - "./volumes/datadir:/var/lib/postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vaccination_card_dev
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"